language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

before_script:
  - mkdir -p build/{logs,coverage/html,testdox}
  - composer self-update
  - composer update --prefer-source --dev

script:
  - ./bin/phpunit

